exclude: 'vendor/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: mixed-line-ending
  - id: end-of-file-fixer
    types: [python]

- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
    args: ["-l 80", "--preview"]

ci:
  autofix_prs: false
