name: docker tests

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false
jobs:
  ubuntu_version_tests2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Trim CI agent
      run: |
        chmod +x contrib/free_disk_space.sh
        ./contrib/free_disk_space.sh
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[dev]
        npm install -g @cyclonedx/cdxgen
        mkdir -p repotests
    - uses: actions/checkout@v4
      with:
        repository: 'GoogleCloudPlatform/microservices-demo'
        path: 'repotests/microservices-demo'
    - uses: actions/checkout@v4
      with:
        repository: 'OWASP/NodeGoat'
        path: 'repotests/NodeGoat'
    - uses: actions/checkout@v4
      with:
        repository: 'juice-shop/juice-shop'
        path: 'repotests/juiceshop'
    - name: Test container images
      run: |
        mkdir -p containertests_${{ matrix.os }}
        python3 -m pip install -r contrib/requirements.txt
        cp contrib/csaf.toml repotests/microservices-demo/csaf.toml
        cp contrib/csaf.toml repotests/NodeGoat/csaf.toml
        cp contrib/csaf.toml repotests/juiceshop/csaf.toml
        python3 depscan/cli.py --csaf --no-banner --no-error --src ${GITHUB_WORKSPACE}/repotests/microservices-demo --reports-dir ${GITHUB_WORKSPACE}/containertests_${{ matrix.os }}/reports/microservices-demo
        python3 depscan/cli.py --csaf --no-banner --no-error --src ${GITHUB_WORKSPACE}/repotests/NodeGoat --reports-dir ${GITHUB_WORKSPACE}/containertests_${{ matrix.os }}/reports/NodeGoat
        python3 depscan/cli.py --csaf --no-banner --no-error --src ${GITHUB_WORKSPACE}/repotests/juiceshop --reports-dir ${GITHUB_WORKSPACE}/containertests_${{ matrix.os }}/reports/juiceshop
      env:
        PYTHONPATH: "."
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VDB_HOME: "vdb_data"
        PYTHONUTF8: 1
    - uses: actions/upload-artifact@v4
      with:
        name: containertests_${{ matrix.os }}
        path: containertests_${{ matrix.os }}
