name: Generate Depscan Snapshots

on:
  workflow_dispatch:


concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true


jobs:

  generate:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      -  name: install depscan
         run: |
           python -m pip install --upgrade pip
           python -m venv venv
           source venv/bin/activate
           pip install .
           vdb --download-image

      - name: Get boms
        run: |
           git clone https://github.com/appthreat/cdxgen-samples.git /home/runner/work/cdxgen-samples
           cd /home/runner/work/cdxgen-samples
           git checkout b5dc7d02548bc8f8983d981dc21de5612e37731c

      - name: Generate snapshots and test
        env:
          DEPSCAN_CSAF_TEMPLATE: "/home/runner/work/dep-scan/dep-scan/contrib/csaf.toml"
          INPUT_THANK_YOU: "I have sponsored OWASP-dep-scan."
        run: |
          mkdir /home/runner/work/new_snapshots
          source venv/bin/activate
          /home/runner/work/dep-scan/dep-scan/test/snapshots.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            /home/runner/work/cdxgen-samples/*.vdr.json
            /home/runner/work/cdxgen-samples/*.csaf_v1.json
